USE Timber
GO
BEGIN TRANSACTION

SELECT DISTINCT [mcpfe-2011].COUNTRY_NAME, Countries.COUNTRY_NAME
FROM [mcpfe-2011]
LEFT OUTER JOIN Countries ON [mcpfe-2011].COUNTRY_NAME = Countries.COUNTRY_NAME
WHERE (STATE_STRUCTURE_NAME = N'A4.6a'
		OR STATE_STRUCTURE_NAME = N'A6.7'
		OR STATE_STRUCTURE_NAME LIKE N'A6.8%'
	)
	AND Countries.COUNTRY_NAME IS NULL

UPDATE [mcpfe-2011]
SET COUNTRY_NAME = N'Moldova, Republic of'
WHERE (STATE_STRUCTURE_NAME = N'A4.6a'
		OR STATE_STRUCTURE_NAME = N'A6.7'
		OR STATE_STRUCTURE_NAME LIKE N'A6.8%'
	)
	AND COUNTRY_NAME = N'Republic of Moldova'

UPDATE [mcpfe-2011]
SET COUNTRY_NAME = N'Slovakia'
WHERE (STATE_STRUCTURE_NAME = N'A4.6a'
		OR STATE_STRUCTURE_NAME = N'A6.7'
		OR STATE_STRUCTURE_NAME LIKE N'A6.8%'
	)
	AND COUNTRY_NAME = N'Slovak Republic'

UPDATE [mcpfe-2011]
SET COUNTRY_NAME = N'The former Yugoslav Republic of Macedonia'
WHERE (STATE_STRUCTURE_NAME = N'A4.6a'
		OR STATE_STRUCTURE_NAME = N'A6.7'
		OR STATE_STRUCTURE_NAME LIKE N'A6.8%'
	)
	AND COUNTRY_NAME = N'The fYR of Macedonia'

SELECT DISTINCT [mcpfe-2011].COUNTRY_NAME, Countries.COUNTRY_NAME
FROM [mcpfe-2011]
LEFT OUTER JOIN Countries ON [mcpfe-2011].COUNTRY_NAME = Countries.COUNTRY_NAME
WHERE (STATE_STRUCTURE_NAME = N'A4.6a'
		OR STATE_STRUCTURE_NAME = N'A6.7'
		OR STATE_STRUCTURE_NAME LIKE N'A6.8%'
	)
	AND Countries.COUNTRY_NAME IS NULL

ROLLBACK TRANSACTION
--COMMIT TRANSACTION
GO