USE Timber
GO
BEGIN TRANSACTION

--DELETE FROM [mcpfe-2011]
SELECT * FROM [mcpfe-2011]
WHERE STATE_STRUCTURE_NAME = N'A3.3a'
	OR STATE_STRUCTURE_NAME = N'A3.3b'

ROLLBACK TRANSACTION
--COMMIT TRANSACTION
GO