USE Timber
GO
SELECT COUNTRY_NAME,
	STATE_STRUCTURE_NAME,
	TERM_NAME,
	YEAR,
	DATA,
	Uploaded
FROM [mcpfe-2011]
WHERE STATE_STRUCTURE_NAME = N'F3.2'
	AND ((Uploaded <> N'yes')
		OR (Uploaded IS NULL)
	)
ORDER BY TERM_NAME
GO
SELECT TERM_NAME,
	COUNT(*) AS COUNT_TERM_NAME
FROM [mcpfe-2011]
WHERE STATE_STRUCTURE_NAME = N'F3.2'
	AND ((Uploaded <> N'yes')
		OR (Uploaded IS NULL)
	)
GROUP BY TERM_NAME
ORDER BY TERM_NAME
GO