USE Timber
GO
SELECT --STATE_STRUCTURE_NAME,
	--YEAR,
	COUNTRY_NAME,
	COUNT(DATA) AS 'COUNT DATA'
FROM [mcpfe-2011]
--GROUP BY YEAR, STATE_STRUCTURE_NAME, DATA
GROUP BY STATE_STRUCTURE_NAME, COUNTRY_NAME, DATA
HAVING STATE_STRUCTURE_NAME = N'F1.3a'
	AND DATA = N'-'
GO